# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty
language: cpp

# add PPAs with more up-to-date toolchains
# install toolchains
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-dev
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - libboost-dev
            - g++-5
      env: COMPILER=g++-5

addons:
  apt:
    sources:
        - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
    # install boost
    - libboost-dev
        - cmake
        - cmake-data
    
before_script:
  - git clone https://github.com/Itseez/opencv.git
  - cd opencv
  - mkdir build
  - cd build
  - cmake ..
  - make -j4
  - sudo make -j4 install
  - cd ../..

script:
- mkdir build
- cd build
- cmake ..
- make

