# Ubuntu 14.04 Trusty support
sudo: required
dist: trusty

language:
    cpp
# add PPAs with more up-to-date toolchains
# install toolchains
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5

addons:
  apt:
    sources:
    packages:
    # install boost
    - libboost-dev

before_install:
- git submodule update --init

before_script:

script:
- mkdir build
- cd build
- cmake ..
- make

